pragma Singleton
pragma ComponentBehavior: Bound
import QtQuick
import Quickshell

// Generated by matugen — do not edit manually
Singleton {
    id: root

    // Primary
    readonly property color primary: "#d0bdfe"
    readonly property color primaryOn: "#36265d"
    readonly property color primaryContainer: "#4d3d75"
    readonly property color primaryContainerOn: "#e9ddff"

    // Secondary
    readonly property color secondary: "#ccc2db"
    readonly property color secondaryOn: "#332d41"
    readonly property color secondaryContainer: "#4a4458"
    readonly property color secondaryContainerOn: "#e8def8"

    // Tertiary
    readonly property color tertiary: "#efb8c8"
    readonly property color tertiaryOn: "#4a2532"
    readonly property color tertiaryContainer: "#633b48"
    readonly property color tertiaryContainerOn: "#ffd9e2"

    // Error
    readonly property color error: "#ffb4ab"
    readonly property color errorOn: "#690005"
    readonly property color errorContainer: "#93000a"
    readonly property color errorContainerOn: "#ffdad6"

    // Surface
    readonly property color background: "#141218"
    readonly property color backgroundOn: "#e6e0e9"
    readonly property color surface: "#141218"
    readonly property color surfaceOn: "#e6e0e9"
    readonly property color surfaceVariant: "#49454e"
    readonly property color surfaceVariantOn: "#cac4cf"
    readonly property color surfaceContainer: "#211f24"
    readonly property color surfaceContainerLow: "#1d1b20"
    readonly property color surfaceContainerHigh: "#2b292f"
    readonly property color surfaceContainerHighest: "#36343a"
    readonly property color surfaceContainerLowest: "#0f0d13"

    // Outline / misc
    readonly property color outline: "#948f99"
    readonly property color outlineVariant: "#49454e"
    readonly property color inverseSurface: "#e6e0e9"
    readonly property color inverseSurfaceOn: "#322f35"
    readonly property color inversePrimary: "#65558f"
    readonly property color shadow: "#000000"
    readonly property color scrim: "#000000"
}
