pragma Singleton
pragma ComponentBehavior: Bound
import QtQuick
import Quickshell

// Generated by matugen — do not edit manually
Singleton {
    id: root

    // Primary
    readonly property color primary: "#ffb3ae"
    readonly property color primaryOn: "#571d1c"
    readonly property color primaryContainer: "#733331"
    readonly property color primaryContainerOn: "#ffdad7"

    // Secondary
    readonly property color secondary: "#e7bdb9"
    readonly property color secondaryOn: "#442928"
    readonly property color secondaryContainer: "#5d3f3d"
    readonly property color secondaryContainerOn: "#ffdad7"

    // Tertiary
    readonly property color tertiary: "#e2c28c"
    readonly property color tertiaryOn: "#402d04"
    readonly property color tertiaryContainer: "#594319"
    readonly property color tertiaryContainerOn: "#ffdea7"

    // Error
    readonly property color error: "#ffb4ab"
    readonly property color errorOn: "#690005"
    readonly property color errorContainer: "#93000a"
    readonly property color errorContainerOn: "#ffdad6"

    // Surface
    readonly property color background: "#1a1111"
    readonly property color backgroundOn: "#f1dedd"
    readonly property color surface: "#1a1111"
    readonly property color surfaceOn: "#f1dedd"
    readonly property color surfaceVariant: "#534342"
    readonly property color surfaceVariantOn: "#d8c2c0"
    readonly property color surfaceContainer: "#271d1d"
    readonly property color surfaceContainerLow: "#231919"
    readonly property color surfaceContainerHigh: "#322827"
    readonly property color surfaceContainerHighest: "#3d3231"
    readonly property color surfaceContainerLowest: "#140c0c"

    // Outline / misc
    readonly property color outline: "#a08c8b"
    readonly property color outlineVariant: "#534342"
    readonly property color inverseSurface: "#f1dedd"
    readonly property color inverseSurfaceOn: "#382e2d"
    readonly property color inversePrimary: "#904a46"
    readonly property color shadow: "#000000"
    readonly property color scrim: "#000000"
}
